### ISSUE TITLE
Screenshot is cropped

### ISSUE THREAD

**Issue by nescriu** [ph5x5/albion-minimap-overlay#1]
Version: 0.4.1
Resolution: 1920x1080

The screenshot region is moved to the right and i can't find an option to adjust on the config file.

![screenshot](https://user-images.githubusercontent.com/5109287/58375330-76cad580-7f26-11e9-9800-36dfcd217b52.png)

**Comment by ph5x5** [comment]
Could you try version 0.4.2 please?
Do you have the borderless fullscreen option on?
Also, please check the Interface scaling option in the game settings, it must be 80%.

**Comment by nescriu** [comment]
Thanks it is working now, i think you should add to the readme that scaling must be at 80%.

**Comment by ph5x5** [comment]
Thank you for finding this!
