### ISSUE TITLE
still technically a violation.. but.. 

### ISSUE THREAD

**Issue by gamedumb** [ph5x5/albion-minimap-overlay#11]
instead of creating an overlay, would placing it in a second window (as an option?) that could be scaled and moved around to wherever the player wanted with an always on top option be a workaround? i would use it on mon. 2 personally

**Comment by ph5x5** [comment]
You can use the Albion2D map database then instead: https://www.albiononline2d.com/en/map/0218

**Comment by gamedumb** [comment]
i dont believe that info is updated very well, i run the data client and watch that map but it does not often actually point me to nodes. this is why i was hoping to use something like this, real time data based on my actions... and automated. you have all the features but one lol. i dont want to risk getting an account ive paid in to banned for any reason. 
thanks for the reply!
